name: CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: ['7.2', '7.3', '7.4']
        name: PHP ${{ matrix.php-version }}
        steps:
            -   uses: actions/checkout@v1
            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    tools: pecl, composer:v1
                    extensions: mongodb-1.6.1
            -   name: PHP version
                run: php -v
