name: CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: ['7.2']
        name: PHP ${{ matrix.php-version }}
        steps:
            -   uses: actions/checkout@v1
            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: 'none'
                    php-version: ${{ matrix.php-version }}
                    tools: pecl, composer:v1
                    extensions: mongodb-1.6.1
            -   name: Composer install
                run: 'composer install --no-interaction --no-progress --no-suggest'
            -   name: PhpUnit
                run: ./vendor/bin/phpunit

